### ISSUE TITLE
Container not running after no previous issues

### ISSUE THREAD

**Issue by tzacher16** [haugene/docker-transmission-openvpn#1341]
**Describe the problem**

I have had Transmission installed for a few months now on a Raspberry Pi 4 and had no issues, up until yesterday. I've spent all day reading here and trying to troubleshoot to no avail. The container itself will start and read as "healthy" but it doesn't look like Transmission or the web UI are working. I even tried testing in Radarr to see if it was working, but those tests failed as well. I even deleted and re-set up a new container with the same settings as before.

I did find the following repeating message in the transmission.log in the transmission-home folder on the Raspberry Pi
"RPC Server Couldn't find settings key "rpc-port" (rpc-server.c:1117)"

**Add your docker run command**
docker run --cap-add=NET_ADMIN -d \
              -v  /mnt/plexdrive/transmission:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=TORGUARD \
              -e OPENVPN_CONFIG=CA\ Toronto \
              -e OPENVPN_USERNAME=username \
              -e OPENVPN_PASSWORD=password \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.0.1/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn:dev-armhf

**Logs**
Using OpenVPN provider: TORGUARD
Supplied config CA Toronto.ovpn could not be found.
Using default OpenVPN gateway for provider torguard
Setting OPENVPN credentials...
adding route to local network 192.168.0.1/24 via 172.17.0.1 dev eth0
Error: Invalid prefix for given prefix length.
Sun Aug 23 19:04:32 2020 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Sun Aug 23 19:04:32 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Sun Aug 23 19:04:32 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun Aug 23 19:04:32 2020 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Sun Aug 23 19:04:32 2020 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Sun Aug 23 19:04:32 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.80.220.184:1912
Sun Aug 23 19:04:32 2020 Socket Buffers: R=[180224->360448] S=[180224->360448]
Sun Aug 23 19:04:32 2020 UDP link local: (not bound)
Sun Aug 23 19:04:32 2020 UDP link remote: [AF_INET]185.80.220.184:1912
Sun Aug 23 19:04:32 2020 TLS: Initial packet from [AF_INET]185.80.220.184:1912, sid=fd4bd750 73b29506
Sun Aug 23 19:04:32 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Aug 23 19:04:32 2020 VERIFY OK: depth=1, CN=TG-VPN-CA
Sun Aug 23 19:04:32 2020 VERIFY KU OK
Sun Aug 23 19:04:32 2020 Validating certificate extended key usage
Sun Aug 23 19:04:32 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sun Aug 23 19:04:32 2020 VERIFY EKU OK
Sun Aug 23 19:04:32 2020 VERIFY OK: depth=0, CN=server
Sun Aug 23 19:04:33 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1582', remote='link-mtu 1569'
Sun Aug 23 19:04:33 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'
Sun Aug 23 19:04:33 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
Sun Aug 23 19:04:33 2020 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-GCM', remote='cipher AES-128-CBC'
Sun Aug 23 19:04:33 2020 WARNING: 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA256'
Sun Aug 23 19:04:33 2020 WARNING: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
Sun Aug 23 19:04:33 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
Sun Aug 23 19:04:33 2020 [server] Peer Connection Initiated with [AF_INET]185.80.220.184:1912
Sun Aug 23 19:04:34 2020 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Sun Aug 23 19:04:34 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.9.0.1,dhcp-option DNS 10.8.0.1,sndbuf 524288,rcvbuf 524288,route 10.35.0.1,topology net30,ping 5,ping-restart 30,compress,ifconfig 10.35.0.22 10.35.0.21,peer-id 8'
Sun Aug 23 19:04:34 2020 OPTIONS IMPORT: timers and/or timeouts modified
Sun Aug 23 19:04:34 2020 OPTIONS IMPORT: compression parms modified
Sun Aug 23 19:04:34 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Sun Aug 23 19:04:34 2020 Socket Buffers: R=[360448->360448] S=[360448->360448]
Sun Aug 23 19:04:34 2020 OPTIONS IMPORT: --ifconfig/up options modified
Sun Aug 23 19:04:34 2020 OPTIONS IMPORT: route options modified
Sun Aug 23 19:04:34 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sun Aug 23 19:04:34 2020 OPTIONS IMPORT: peer-id set
Sun Aug 23 19:04:34 2020 OPTIONS IMPORT: adjusting link_mtu to 1657
Sun Aug 23 19:04:34 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Aug 23 19:04:34 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Aug 23 19:04:34 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:07
Sun Aug 23 19:04:34 2020 TUN/TAP device tun0 opened
Sun Aug 23 19:04:34 2020 TUN/TAP TX queue length set to 100
Sun Aug 23 19:04:34 2020 /sbin/ip link set dev tun0 up mtu 1500
Sun Aug 23 19:04:34 2020 /sbin/ip addr add dev tun0 local 10.35.0.22 peer 10.35.0.21
Sun Aug 23 19:04:34 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1585 10.35.0.22 10.35.0.21 init
Up script executed with tun0 1500 1585 10.35.0.22 10.35.0.21 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.35.0.22
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding alt-speed-down because TRANSMISSION_ALT_SPEED_DOWN is set to 50
Overriding alt-speed-enabled because TRANSMISSION_ALT_SPEED_ENABLED is set to false
Overriding alt-speed-time-begin because TRANSMISSION_ALT_SPEED_TIME_BEGIN is set to 540
Overriding alt-speed-time-day because TRANSMISSION_ALT_SPEED_TIME_DAY is set to 127
Overriding alt-speed-time-enabled because TRANSMISSION_ALT_SPEED_TIME_ENABLED is set to false
Overriding alt-speed-time-end because TRANSMISSION_ALT_SPEED_TIME_END is set to 1020
Overriding alt-speed-up because TRANSMISSION_ALT_SPEED_UP is set to 50
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.35.0.22
Overriding bind-address-ipv6 because TRANSMISSION_BIND_ADDRESS_IPV6 is set to ::
Overriding blocklist-enabled because TRANSMISSION_BLOCKLIST_ENABLED is set to false
Overriding blocklist-url because TRANSMISSION_BLOCKLIST_URL is set to http://www.example.com/blocklist
Overriding cache-size-mb because TRANSMISSION_CACHE_SIZE_MB is set to 4
Overriding dht-enabled because TRANSMISSION_DHT_ENABLED is set to true
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding download-limit because TRANSMISSION_DOWNLOAD_LIMIT is set to 100
Overriding download-limit-enabled because TRANSMISSION_DOWNLOAD_LIMIT_ENABLED is set to 0
Overriding download-queue-enabled because TRANSMISSION_DOWNLOAD_QUEUE_ENABLED is set to true
Overriding download-queue-size because TRANSMISSION_DOWNLOAD_QUEUE_SIZE is set to 5
Overriding encryption because TRANSMISSION_ENCRYPTION is set to 1
Overriding idle-seeding-limit because TRANSMISSION_IDLE_SEEDING_LIMIT is set to 30
Overriding idle-seeding-limit-enabled because TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED is set to false
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding incomplete-dir-enabled because TRANSMISSION_INCOMPLETE_DIR_ENABLED is set to true
Overriding lpd-enabled because TRANSMISSION_LPD_ENABLED is set to false
Overriding max-peers-global because TRANSMISSION_MAX_PEERS_GLOBAL is set to 200
Overriding message-level because TRANSMISSION_MESSAGE_LEVEL is set to 2
Overriding peer-congestion-algorithm because TRANSMISSION_PEER_CONGESTION_ALGORITHM is set to
Overriding peer-id-ttl-hours because TRANSMISSION_PEER_ID_TTL_HOURS is set to 6
Overriding peer-limit-global because TRANSMISSION_PEER_LIMIT_GLOBAL is set to 200
Overriding peer-limit-per-torrent because TRANSMISSION_PEER_LIMIT_PER_TORRENT is set to 50
Overriding peer-port because TRANSMISSION_PEER_PORT is set to 51413
Overriding peer-port-random-high because TRANSMISSION_PEER_PORT_RANDOM_HIGH is set to 65535
Overriding peer-port-random-low because TRANSMISSION_PEER_PORT_RANDOM_LOW is set to 49152
Overriding peer-port-random-on-start because TRANSMISSION_PEER_PORT_RANDOM_ON_START is set to false
Overriding peer-socket-tos because TRANSMISSION_PEER_SOCKET_TOS is set to default
Overriding pex-enabled because TRANSMISSION_PEX_ENABLED is set to true
Overriding port-forwarding-enabled because TRANSMISSION_PORT_FORWARDING_ENABLED is set to true
Overriding preallocation because TRANSMISSION_PREALLOCATION is set to 1
Overriding prefetch-enabled because TRANSMISSION_PREFETCH_ENABLED is set to 1
Overriding queue-stalled-enabled because TRANSMISSION_QUEUE_STALLED_ENABLED is set to true
Overriding queue-stalled-minutes because TRANSMISSION_QUEUE_STALLED_MINUTES is set to 30
Overriding ratio-limit because TRANSMISSION_RATIO_LIMIT is set to 2
Overriding ratio-limit-enabled because TRANSMISSION_RATIO_LIMIT_ENABLED is set to false
Overriding rename-partial-files because TRANSMISSION_RENAME_PARTIAL_FILES is set to true
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to false
Overriding rpc-bind-address because TRANSMISSION_RPC_BIND_ADDRESS is set to 0.0.0.0
Overriding rpc-enabled because TRANSMISSION_RPC_ENABLED is set to true
Overriding rpc-host-whitelist because TRANSMISSION_RPC_HOST_WHITELIST is set to
Overriding rpc-host-whitelist-enabled because TRANSMISSION_RPC_HOST_WHITELIST_ENABLED is set to false
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to password
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-url because TRANSMISSION_RPC_URL is set to /transmission/
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to username
Overriding rpc-whitelist because TRANSMISSION_RPC_WHITELIST is set to 172.17.0.1
Overriding rpc-whitelist-enabled because TRANSMISSION_RPC_WHITELIST_ENABLED is set to true
Overriding scrape-paused-torrents-enabled because TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED is set to true
Overriding script-torrent-done-enabled because TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED is set to false
Overriding script-torrent-done-filename because TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME is set to
Overriding seed-queue-enabled because TRANSMISSION_SEED_QUEUE_ENABLED is set to false
Overriding seed-queue-size because TRANSMISSION_SEED_QUEUE_SIZE is set to 10
Overriding speed-limit-down because TRANSMISSION_SPEED_LIMIT_DOWN is set to 100
Overriding speed-limit-down-enabled because TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED is set to false
Overriding speed-limit-up because TRANSMISSION_SPEED_LIMIT_UP is set to 100
Overriding speed-limit-up-enabled because TRANSMISSION_SPEED_LIMIT_UP_ENABLED is set to false
Overriding start-added-torrents because TRANSMISSION_START_ADDED_TORRENTS is set to true
Overriding trash-original-torrent-files because TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES is set to false
Overriding umask because TRANSMISSION_UMASK is set to 2
Overriding upload-slots-per-torrent because TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT is set to 14
Overriding utp-enabled because TRANSMISSION_UTP_ENABLED is set to false
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
Overriding watch-dir-enabled because TRANSMISSION_WATCH_DIR_ENABLED is set to true
Overriding watch-dir-force-generic because TRANSMISSION_WATCH_DIR_FORCE_GENERIC is set to false
sed'ing True to true

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
Transmission startup script complete.
Sun Aug 23 19:04:35 2020 /sbin/ip route add 185.80.220.184/32 via 172.17.0.1
Sun Aug 23 19:04:35 2020 /sbin/ip route add 0.0.0.0/1 via 10.35.0.21
Sun Aug 23 19:04:35 2020 /sbin/ip route add 128.0.0.0/1 via 10.35.0.21
Sun Aug 23 19:04:35 2020 /sbin/ip route add 10.35.0.1/32 via 10.35.0.21
Sun Aug 23 19:04:35 2020 Initialization Sequence Completed

**Host system:**
Raspberry Pi 4

**Comment by pkishino** [comment]
most likely transmission is running just fine, just that you cannot access it.
try to ssh into the container and check with ps or top if transmission and openvpn are both running.
also check if the 9091 port is open
also check the transmission settings if the rpc-port setting is there and has the 9091 value, seems like there is some problem there
which version are you using ??

**Comment by tzacher16** [comment]
So forgive me here, I'm still not the most savvy with doing these kinds of things...

- Running "docker container ls" shows that the transmission container is running and healthy
- Running "sudo iptables -L" shows the following for the port:
`ACCEPT     tcp  --  anywhere             172.17.0.6           tcp dpt:9091`
- I checked the Portainer interface as well and it showed it was healthy with the last output as follows:
`PING google.com (172.217.17.78) 56(84) bytes of data. 64 bytes from ams16s30-in-f14.1e100.net (172.217.17.78): icmp_seq=1 ttl=117 time=101 ms --- google.com ping statistics --- 1 packets transmitted, 1 received, 0% packet loss, time 0ms rtt min/avg/max/mdev = 100.642/100.642/100.642/0.000 ms Network is up Openvpn and transmission-daemon processes are running`
- Looks like the current version of the container is 4.0.0+balena2-arm?

I can share my entire settings in portainer as well if you think that would help.

**Comment by pkishino** [comment]
if your using portainer, use the console of the container to get inside and check

**Comment by tzacher16** [comment]
No dice on either of those. The local network setting when it was working before was 192.168.0.1/24 

Here's the full settings.json file:
{
    "alt-speed-down": 0,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 0,
    "alt-speed-time-day": 0,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 0,
    "alt-speed-up": 0,
    "bind-address-ipv4": "10.35.0.6",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 2,
    "dht-enabled": true,
    "download-dir": "/data/completed",
    "download-limit": "100",
    "download-limit-enabled": "0",
    "download-queue-enabled": true,
    "download-queue-size": 0,
    "encryption": 0,
    "idle-seeding-limit": 0,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/data/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "max-peers-global": "200",
    "message-level": 1,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 0,
    "peer-limit-global": 0,
    "peer-limit-per-torrent": 0,
    "peer-port": 0,
    "peer-port-random-high": 0,
    "peer-port-random-low": 0,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": false,
    "preallocation": 0,
    "prefetch-enabled": false,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 0,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": "false",
    "rpc-password": "{8cf4d93bebcdd78aac6e685e27d405ef92c0096a0JEvpdli",
    "rpc-port": 0,
    "rpc-url": "/transmission/",
    "rpc-username": "username",
    "rpc-whitelist": "172.17.0.1",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 0,
    "speed-limit-down": 0,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 0,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 0,
    "upload-slots-per-torrent": 0,
    "utp-enabled": false,
    "watch-dir": "/data/watch",
    "watch-dir-enabled": "true",
    "watch-dir-force-generic": "false"
}

**Comment by pkishino** [comment]
hmmm.. anyway,
as you can see, rpc port is set to 0
also, umask is 0..

**Comment by pkishino** [comment]
somehow your settings look messed up and not using the defaults..
@haugene could this be due to latest update?
Error: Invalid prefix for given prefix length also doesnt look good..
Did you get same error with other local_network setting?

**Comment by tzacher16** [comment]
Odd. I had both of those set in the portainer view to 9091 and 2, respectively

**Comment by pkishino** [comment]
have you tried to wipe the image+storage in portainer, might be some old data somehow..

**Comment by tzacher16** [comment]
Just tried now. Cleared image out of portainer and manually wiped all old data from the pi itself. Still getting the same rpc port error

**Comment by haugene** [comment]
Oh, sorry guys. This is probably my fault. Haven't read everything in detail but the funky overriding of settings is at least some bug with the new settings script. Thank you for testing it though, it is valuable input @tzacher16. Needs more hardening before getting merged to master.

I understand if you want to switch image over to `latest-armhf` instead of `dev-armhf` as that would probably work as it used to. But if you have the time to test a couple of more iterations we might get this going with the new setup. I don't have a Pi myself and I'm dependant on someone using this to test it all before we merge some time.

I have now pushed changes that will update the arm image as well, removing a lot of the default environment variables. Now this will not fix the script but limit it's short comings. Can you pull the dev-armhf and try again?

**Comment by tzacher16** [comment]
So I did switch to latest-armhf. It looks like the transmission downloader is now working, but I'm still unable to access the WebUI right now. I haven't tried changing too much yet (wanted to get the downloader working first) but this is definitely good progress!

**Comment by tzacher16** [comment]
Changed some more settings around and everything is running smoothly!  Gonna close this out.

**Comment by haugene** [comment]
Great that you got it working. I am going to merge the changes from dev into master at some point. Hopefully by then the scripts will be more stable and we won't have these issues. If not then I guess you'll be back with this issue and we will have to manage it then 😄
