### ISSUE TITLE
Vyprvpn provider

### ISSUE THREAD

**Issue by starsys** [haugene/docker-transmission-openvpn#151]
Hello.
I'm just discovering Docker and all its possibilities.
I'd like to use transmission with Vyprvpn on my DS 411 II+ Nas.
Until now I cannot make it work, as it seems I've to set different settings as explained on the hub.docker page.
I'm not so familiar with all these tweaks, I hope I'll manage to do it (if anyone can, help me, I would really appreciate and thanks).
I cannot see any Vyprvpn configuration. 
Is it please possible to add it ?
Thanks again in advance.

**Comment by pkishino** [comment]
can you provide a link to the ovpn files from vypr please?

**Comment by starsys** [comment]
Hello.
Thanks a lot for your help.

The config page is here:
https://support.goldenfrog.com/hc/en-us/articles/204088673-VyprVPN-OpenVPN-Setup-for-Synology-NAS


2016-10-15 17:40 GMT+02:00 Patrick Kishino <notifications@github.com>:

**Comment by starsys** [comment]
Hello.
Let me know if you need something else.

**Comment by haugene** [comment]
Most providers have a .zip file with all the .ovpn configuration files. If you can find that and post the link here, that would be great...

**Comment by starsys** [comment]
Hello Kristian.
Here it is.

Thanks.

2016-10-16 22:11 GMT+02:00 Kristian Haugene <notifications@github.com>:

**Comment by haugene** [comment]
Can't see that your comment contained any link to configs. Seems like you're replying by mail, don't think GitHub supports attachments if that's what you're up to...

**Comment by starsys** [comment]
Hello.
You can download open vpn files here :
https://support.goldenfrog.com/hc/en-us/articles/225607167-Where-can-I-find-the-OpenVPN-files-

Le lundi 17 octobre 2016, Kristian Haugene <notifications@github.com> a
écrit :

**Comment by starsys** [comment]
Hello Patrick. I'm not sure to have well understood your last mail. Have
you everything what you need ?

**Comment by haugene** [comment]
Yes he did :) Patrick fixed it and I've now merged his pull request to the development branch.

You should be able to use VyperVPN as provider using `OPENVPN_PROVIDER=VYPERVPN` and image `haugene/transmission-openvpn:dev`

Shout out when you've tested it if it works as expected ;)

**Comment by starsys** [comment]
Hello.
I'm a newbee regarding docker.
Would you accept to help me a bit ?
I tried following command line via SSH on my synology NAS :

 docker pull haugene/transmission-openvpn:dev
Warning: failed to get default registry endpoint from daemon (Cannot
connect to the Docker daemon. Is the docker daemon running on this host?).
Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon. Is the docker daemon running on this
host?

It seems that Docker isn't running (or maybe I'm wrong). But the synology
Docker app is running on my nas.
What should I do to retreive your dev version ?

I also tried via the GUI by trying to import the github zip file of the
docker:dev repository but it doesn't works either...

Thanks in advance for your help.

2016-10-19 23:47 GMT+02:00 Kristian Haugene <notifications@github.com>:

**Comment by haugene** [comment]
Hey, sorry for the delay. Did you figure it out? I'm guessing this is because you're running the `docker pull` as a non-root user which does not have access to the Docker socket.

Try running the command as root or with sudo. Depending on how docker is set up and the linux distro used, adding your user to the docker group (if it exists) might also fix this. But try with root, should do the trick.

**Comment by starsys** [comment]
Hello Krisitan.
Thanks !

root@DS411:~# docker pull haugene/transmission-openvpn:dev
dev: Pulling from haugene/transmission-openvpn

bf5d46315322: Pull complete
9f13e0ac480c: Pull complete
e8988b5b3097: Pull complete
40af181810e7: Pull complete
e6f7c7e5c03e: Pull complete
704c074f71a4: Download complete
77e8dfb15ba5: Download complete
b303123cc557: Download complete

I try to continue the installation

2016-11-11 12:52 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by starsys** [comment]
I downloaded sucessfully the image and made it run as container.
I still cannot reach the http://local_adress:9091 page
Can you please tell me which variable table I should use for OPENVPN_CONFIG
parameter ? (for France is it "France - Paris" ?)

Now I've to do that :

Here are the steps to run it on a Synology NAS (Tested on DSM 6) :

   - Connect as *admin* to your Synology SSH
   - Switch to root with command sudo su -
   - Enter your *admin* password when prompted
   - Create a TUN.sh file anywhere in your synology file system by typing vim
   /volume1/foldername/TUN.sh replacing *foldername* with any folder you
   created on your Synology
   - Paste @timkelty 's script :

#!/bin/sh

# Create the necessary file structure for /dev/net/tun
if ( [ ! -c /dev/net/tun ] ); then
    if ( [ ! -d /dev/net ] ); then
        mkdir -m 755 /dev/net
    fi
    mknod /dev/net/tun c 10 200
fi

# Load the tun module if not already loaded
if ( !(lsmod | grep -q "^tun\s") ); then
    insmod /lib/modules/tun.ko
fi


   - Save the file with [escape] + :wq!
   - Go in the folder containing your script : cd /volume1/foldername/
   - Check permission with chmod 0755 TUN.sh
   - Run it with ./TUN.sh
   - Return to initial directory typing cd
   - Create the DNS config file by typing vim
   /volume1/foldername/resolv.conf
   - Paste the following lines :

nameserver 8.8.8.8
nameserver 8.8.4.4


   - Save the file with [escape] + :wq!
   - Create your docker container with a classic command like docker run
   --privileged -d -v /volume1/foldername/resolv.conf:/etc/resolv.conf -v
   /volume1/yourpath/:/data -e "OPENVPN_PROVIDER=PIA" -e
   "OPENVPN_CONFIG=Netherlands" -e "OPENVPN_USERNAME=XXXXX" -e
   "OPENVPN_PASSWORD=XXXXX" -p 9091:9091 --name "TransmissionVPN"
   haugene/transmission-openvpn
   - To make it work after a nas restart, create an automated task in your
   synology web interface : go to **Settings Panel > Task Scheduler **
   create a new task that run /volume1/foldername/TUN.sh as root (select '
   *root*' in 'user' selectbox). This task will start module that permit
   the container to run, you can make a task that run on startup. These kind
   of task doesn't work on my nas so I just made a task that run every minute.
   - Enjoy

As I use the GUI of Docker on my NAS, can you please tell me how I set this
section in the GUI : /volume1/foldername/resolv.conf:/etc/resolv.conf -v
/volume1/yourpath/ ?

Thanks again

2016-11-11 12:52 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by starsys** [comment]
I've created the TUN.sh as explained but I cannot make it works.
I tried to create my docker container with docker command line but this
container doesn't start.

Can you please tell me what should I use a variable vor VYPERVPN OPENVPN_CONFIG
?
Thanks in advance.

2016-11-13 14:50 GMT+01:00 Théophile Guettier <theophile.guettier@gmail.com>
:

**Comment by pkishino** [comment]
what run command are you using now? please check the readme and it will tell you the details.
as provider just type =VYPERVPN and for config check the files in the vypervpn config folder, should tell you which name you can use.
As for the GUI I don't know, I only run command line, why not try that instead?

**Comment by haugene** [comment]
You're not setting the LOCAL_NETWORK environment variable? See the readme for how to access the web ui.

**Comment by starsys** [comment]
Hello Kristian. Sorry for late answer, I was in Germany.

Here is the command I try to run without success :
docker run --privileged -d -v /volume1/tmp/resolv.conf:/etc/resolv.conf -v
/volume1/tmp/:/data -e "OPENVPN_PROVIDER=VYPRVPN" -e
"OPENVPN_CONFIG=France-160" -e "OPENVPN_USERNAME=myusername" -e
"OPENVPN_PASSWORD=mypassword" -p 9091:9091 --name "TransmissionVPN"
haugene/transmission-openvpn:dev

It crashes after few seconds... Do you have any idea ?

2016-11-16 18:05 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by haugene** [comment]
Please provide the logs. Hard to say what's going on without them.

**Comment by starsys** [comment]
Hello Krisitan.
It was not easy for me to find the log file but here it is.
Thanks for your help

2016-11-26 17:23 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by pkishino** [comment]
?did you try to attach it ? not showing up here on github

**Comment by starsys** [comment]
Yes I attached it. I copy it's content directly:
2016-10-15T11:51:27+02:00 DS411 docker[7863]: WARN[0002] Running modprobe nf_nat failed with message: ``, error: exit status 1 
2016-10-15T11:51:27+02:00 DS411 docker[7863]: WARN[0002] Running modprobe xt_conntrack failed with message: ``, error: exit status 1 
2016-10-15T11:51:28+02:00 DS411 docker[7863]: WARN[0003] Your kernel does not support kernel memory limit. 
2016-10-15T11:51:28+02:00 DS411 docker[7863]: WARN[0003] Your kernel does not support cgroup cfs period 
2016-10-15T11:51:28+02:00 DS411 docker[7863]: WARN[0003] Your kernel does not support cgroup cfs quotas 
2016-10-15T11:51:28+02:00 DS411 docker[7863]: WARN[0003] Your kernel does not support cgroup blkio weight 
2016-10-15T11:51:28+02:00 DS411 docker[7863]: WARN[0003] Your kernel does not support cgroup blkio weight_device 
2016-10-15T11:51:28+02:00 DS411 docker[7863]: WARN[0003] Your kernel does not support cgroup blkio throttle.read_bps_device 
2016-10-15T11:51:28+02:00 DS411 docker[7863]: WARN[0003] Your kernel does not support cgroup blkio throttle.write_bps_device 
2016-10-15T11:51:28+02:00 DS411 docker[7863]: WARN[0003] Your kernel does not support cgroup blkio throttle.read_iops_device 
2016-10-15T11:51:28+02:00 DS411 docker[7863]: WARN[0003] Your kernel does not support cgroup blkio throttle.write_iops_device 
2016-10-15T11:51:28+02:00 DS411 docker[7863]: WARN[0003] mountpoint for pids not found                
2016-10-15T13:00:57+02:00 DS411 docker[7863]: ERRO[4172] Handler for GET /containers/baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126/top returned error: Container baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126 is restarting, wait until the container is running 
2016-10-15T13:01:01+02:00 DS411 docker[7863]: ERRO[4175] Handler for GET /containers/baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126/top returned error: Container baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126 is restarting, wait until the container is running 
2016-10-15T13:01:04+02:00 DS411 docker[7863]: ERRO[4179] Handler for GET /containers/baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126/top returned error: Container baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126 is restarting, wait until the container is running 
2016-10-15T13:01:07+02:00 DS411 docker[7863]: ERRO[4182] Handler for GET /containers/baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126/top returned error: Container baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126 is restarting, wait until the container is running 
2016-10-15T13:01:10+02:00 DS411 docker[7863]: ERRO[4185] Handler for GET /containers/baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126/top returned error: Container baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126 is restarting, wait until the container is running 
2016-10-15T13:01:14+02:00 DS411 docker[7863]: ERRO[4188] Handler for GET /containers/baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126/top returned error: Container baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126 is restarting, wait until the container is running 
2016-10-15T13:01:17+02:00 DS411 docker[7863]: ERRO[4192] Handler for GET /containers/baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126/top returned error: Container baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126 is restarting, wait until the container is running 
2016-10-15T13:01:20+02:00 DS411 docker[7863]: ERRO[4195] Handler for GET /containers/baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126/top returned error: Container baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126 is restarting, wait until the container is running 
2016-10-15T13:01:23+02:00 DS411 docker[7863]: ERRO[4198] Handler for GET /containers/baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126/top returned error: Container baad36be82f40a141eb0e664e132c5538d44bf21f0de202527c9c54d255c0126 is restarting, wait until the container is running 
2016-10-15T18:04:10+02:00 DS411 docker[7863]: ERRO[22365] Handler for POST /images/load returned error: Untar re-exec error: exit status 1: output: archive/tar: invalid tar header 
2016-10-15T18:45:28+02:00 DS411 docker[12439]: WARN[0036] Running modprobe nf_nat failed with message: ``, error: exit status 1 
2016-10-15T18:45:28+02:00 DS411 docker[12439]: WARN[0036] Running modprobe xt_conntrack failed with message: ``, error: exit status 1 
2016-10-15T18:45:45+02:00 DS411 docker[12439]: WARN[0052] Your kernel does not support kernel memory limit. 
2016-10-15T18:45:45+02:00 DS411 docker[12439]: WARN[0052] Your kernel does not support cgroup cfs period 
2016-10-15T18:45:45+02:00 DS411 docker[12439]: WARN[0052] Your kernel does not support cgroup cfs quotas 
2016-10-15T18:45:45+02:00 DS411 docker[12439]: WARN[0052] Your kernel does not support cgroup blkio weight 
2016-10-15T18:45:45+02:00 DS411 docker[12439]: WARN[0052] Your kernel does not support cgroup blkio weight_device 
2016-10-15T18:45:45+02:00 DS411 docker[12439]: WARN[0052] Your kernel does not support cgroup blkio throttle.read_bps_device 
2016-10-15T18:45:45+02:00 DS411 docker[12439]: WARN[0052] Your kernel does not support cgroup blkio throttle.write_bps_device 
2016-10-15T18:45:45+02:00 DS411 docker[12439]: WARN[0052] Your kernel does not support cgroup blkio throttle.read_iops_device 
2016-10-15T18:45:45+02:00 DS411 docker[12439]: WARN[0052] Your kernel does not support cgroup blkio throttle.write_iops_device 
2016-10-15T18:45:45+02:00 DS411 docker[12439]: WARN[0052] mountpoint for pids not found                
2016-10-17T10:00:17+02:00 DS411 docker[12439]: WARN[141324] container f0c51b9b29908f5303ee24fff92b266f01732bf40fbad559c6b03c05dfccb117 restart canceled 
2016-10-17T10:05:43+02:00 DS411 docker[12439]: WARN[141651] container f0c51b9b29908f5303ee24fff92b266f01732bf40fbad559c6b03c05dfccb117 restart canceled 
2016-10-22T09:16:18+02:00 DS411 docker[12806]: WARN[0010] Running modprobe nf_nat failed with message: ``, error: exit status 1 
2016-10-22T09:16:18+02:00 DS411 docker[12806]: WARN[0010] Running modprobe xt_conntrack failed with message: ``, error: exit status 1 
2016-10-22T09:16:21+02:00 DS411 docker[12806]: WARN[0014] Your kernel does not support kernel memory limit. 
2016-10-22T09:16:21+02:00 DS411 docker[12806]: WARN[0014] Your kernel does not support cgroup cfs period 
2016-10-22T09:16:21+02:00 DS411 docker[12806]: WARN[0014] Your kernel does not support cgroup cfs quotas 
2016-10-22T09:16:21+02:00 DS411 docker[12806]: WARN[0014] Your kernel does not support cgroup blkio weight 
2016-10-22T09:16:21+02:00 DS411 docker[12806]: WARN[0014] Your kernel does not support cgroup blkio weight_device 
2016-10-22T09:16:21+02:00 DS411 docker[12806]: WARN[0014] Your kernel does not support cgroup blkio throttle.read_bps_device 
2016-10-22T09:16:21+02:00 DS411 docker[12806]: WARN[0014] Your kernel does not support cgroup blkio throttle.write_bps_device 
2016-10-22T09:16:21+02:00 DS411 docker[12806]: WARN[0014] Your kernel does not support cgroup blkio throttle.read_iops_device 
2016-10-22T09:16:21+02:00 DS411 docker[12806]: WARN[0014] Your kernel does not support cgroup blkio throttle.write_iops_device 
2016-10-22T09:16:21+02:00 DS411 docker[12806]: WARN[0014] mountpoint for pids not found                
2016-10-22T12:40:12+02:00 DS411 docker[12806]: ERRO[12244] Handler for POST /images/load returned error: Untar re-exec error: exit status 1: output: archive/tar: invalid tar header 
2016-10-22T12:49:22+02:00 DS411 docker[12806]: ERRO[12794] Handler for POST /images/load returned error: Untar re-exec error: exit status 1: output: archive/tar: invalid tar header 
2016-11-13T14:25:51+01:00 DS411 docker[12806]: WARN[1922983] Could not get operating system name: Error opening /usr/lib/os-release: open /usr/lib/os-release: no such file or directory 
2016-11-13T14:27:09+01:00 DS411 docker[12806]: ERRO[1923061] Error trying v2 registry: context canceled   
2016-11-13T14:27:09+01:00 DS411 docker[12806]: ERRO[1923061] Not continuing with pull after error: context canceled 
2016-11-13T14:28:31+01:00 DS411 docker[12806]: WARN[1923143] Could not get operating system name: Error opening /usr/lib/os-release: open /usr/lib/os-release: no such file or directory 
2016-11-13T14:43:36+01:00 DS411 docker[12806]: WARN[1924048] container 6f5c271ee4f5a06596ce4928ef7fb26ce4835b66543ce76e08440b76dd783623 restart canceled 
2016-11-13T14:57:05+01:00 DS411 docker[12956]: WARN[0024] Running modprobe nf_nat failed with message: ``, error: exit status 1 
2016-11-13T14:57:05+01:00 DS411 docker[12956]: WARN[0024] Running modprobe xt_conntrack failed with message: ``, error: exit status 1 
2016-11-13T14:57:09+01:00 DS411 docker[12956]: WARN[0028] Your kernel does not support kernel memory limit. 
2016-11-13T14:57:09+01:00 DS411 docker[12956]: WARN[0028] Your kernel does not support cgroup cfs period 
2016-11-13T14:57:09+01:00 DS411 docker[12956]: WARN[0028] Your kernel does not support cgroup cfs quotas 
2016-11-13T14:57:09+01:00 DS411 docker[12956]: WARN[0028] Your kernel does not support cgroup blkio weight 
2016-11-13T14:57:09+01:00 DS411 docker[12956]: WARN[0028] Your kernel does not support cgroup blkio weight_device 
2016-11-13T14:57:09+01:00 DS411 docker[12956]: WARN[0028] Your kernel does not support cgroup blkio throttle.read_bps_device 
2016-11-13T14:57:09+01:00 DS411 docker[12956]: WARN[0028] Your kernel does not support cgroup blkio throttle.write_bps_device 
2016-11-13T14:57:09+01:00 DS411 docker[12956]: WARN[0028] Your kernel does not support cgroup blkio throttle.read_iops_device 
2016-11-13T14:57:09+01:00 DS411 docker[12956]: WARN[0028] Your kernel does not support cgroup blkio throttle.write_iops_device 
2016-11-13T14:57:09+01:00 DS411 docker[12956]: WARN[0028] mountpoint for pids not found                
2016-11-13T21:41:17+01:00 DS411 docker[12956]: ERRO[24276] Handler for POST /v1.23/containers/create returned error: No such image: haugene/transmission-openvpn:latest 
2016-11-13T21:41:17+01:00 DS411 docker[12956]: WARN[24276] Could not get operating system name: Error opening /usr/lib/os-release: open /usr/lib/os-release: no such file or directory 
2016-11-17T18:07:50+01:00 DS411 docker[12825]: WARN[0015] Running modprobe nf_nat failed with message: ``, error: exit status 1 
2016-11-17T18:07:50+01:00 DS411 docker[12825]: WARN[0015] Running modprobe xt_conntrack failed with message: ``, error: exit status 1 
2016-11-17T18:07:54+01:00 DS411 docker[12825]: WARN[0019] Your kernel does not support kernel memory limit. 
2016-11-17T18:07:54+01:00 DS411 docker[12825]: WARN[0019] Your kernel does not support cgroup cfs period 
2016-11-17T18:07:54+01:00 DS411 docker[12825]: WARN[0019] Your kernel does not support cgroup cfs quotas 
2016-11-17T18:07:54+01:00 DS411 docker[12825]: WARN[0019] Your kernel does not support cgroup blkio weight 
2016-11-17T18:07:54+01:00 DS411 docker[12825]: WARN[0019] Your kernel does not support cgroup blkio weight_device 
2016-11-17T18:07:54+01:00 DS411 docker[12825]: WARN[0019] Your kernel does not support cgroup blkio throttle.read_bps_device 
2016-11-17T18:07:54+01:00 DS411 docker[12825]: WARN[0019] Your kernel does not support cgroup blkio throttle.write_bps_device 
2016-11-17T18:07:54+01:00 DS411 docker[12825]: WARN[0019] Your kernel does not support cgroup blkio throttle.read_iops_device 
2016-11-17T18:07:54+01:00 DS411 docker[12825]: WARN[0019] Your kernel does not support cgroup blkio throttle.write_iops_device 
2016-11-17T18:07:54+01:00 DS411 docker[12825]: WARN[0019] mountpoint for pids not found                
2016-11-26T09:39:25+01:00 DS411 docker[12825]: ERRO[747110] Handler for GET /containers/924af00cab716960c75a9e2392a1da65e114db0c56517a459cb0ae1a77d2fa31/top returned error: rpc error: code = 2 desc = "containerd: container not found"

**Comment by haugene** [comment]
Hi again, sorry for the late reply. These are not the logs I was looking for unfortunately. I understand they were a bit trickier to get as it is the logs from the Docker daemon.

I'm interested in the container logs. And especially from the initialization process. Remove the container and create a new one and then run command `docker logs <container id/name>` 
In your case it seems to be `docker logs TransmissionVPN`

**Comment by starsys** [comment]
Hello.
Here it is :

Could not find OpenVPN provider: VYPRVPN
Please check your settings.
Could not find OpenVPN provider: VYPRVPN
Please check your settings.
Could not find OpenVPN provider: VYPRVPN
Please check your settings.
Using OpenVPN provider: VYPERVPN
Starting OpenVPN using config France-160.ovpn
Setting OPENVPN credentials...
adding route to local network LOCAL_NETWORK=192.168.0.1/253 via 172.17.0.1
dev
e
th0
Error: an inet prefix is expected rather than "LOCAL_NETWORK=192.168.0.1/253
".
Sun Nov 27 13:40:42 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)]
[LZO]
[EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Sun Nov 27 13:40:42 2016 NOTE: the current --script-security setting may
allow
t
his configuration to call user-defined scripts
Sun Nov 27 13:40:42 2016 Socket Buffers: R=[212992->131072]
S=[212992->131072]
Sun Nov 27 13:40:42 2016 UDPv4 link local: [undef]
Sun Nov 27 13:40:42 2016 UDPv4 link remote: [AF_INET]216.166.57.45:1194
Sun Nov 27 13:40:42 2016 TLS: Initial packet from [AF_INET]
216.166.57.45:1194,
s
id=2f07dcfe a98b3282
Sun Nov 27 13:40:42 2016 WARNING: this configuration may cache passwords in
memo
ry -- use the auth-nocache option to prevent this
Sun Nov 27 13:40:42 2016 VERIFY OK: depth=1, C=KY, ST=GrandCayman,
L=GeorgeTown,
O=GoldenFrog-Inc, CN=GoldenFrog-Inc CA, emailAddress=admin@goldenfrog.com
Sun Nov 27 13:40:42 2016 VERIFY X509NAME OK: C=KY, ST=GrandCayman,
L=GeorgeTown,
O=GoldenFrog-Inc, CN=fr1.vyprvpn.com, emailAddress=admin@goldenfrog.com
Sun Nov 27 13:40:42 2016 VERIFY OK: depth=0, C=KY, ST=GrandCayman,
L=GeorgeTown,
O=GoldenFrog-Inc, CN=fr1.vyprvpn.com, emailAddress=admin@goldenfrog.com
Sun Nov 27 13:40:45 2016 Data Channel Encrypt: Cipher 'BF-CBC' initialized
with
128 bit key
Sun Nov 27 13:40:45 2016 Data Channel Encrypt: Using 160 bit message hash
'SHA1'
for HMAC authentication
Sun Nov 27 13:40:45 2016 Data Channel Decrypt: Cipher 'BF-CBC' initialized
with
128 bit key
Sun Nov 27 13:40:45 2016 Data Channel Decrypt: Using 160 bit message hash
'SHA1'
for HMAC authentication
Sun Nov 27 13:40:45 2016 Control Channel: TLSv1, cipher TLSv1/SSLv3
DHE-RSA-AES2
56-SHA, 2048 bit RSA
Sun Nov 27 13:40:45 2016 [fr1.vyprvpn.com] Peer Connection Initiated with
[AF_IN
ET]216.166.57.45:1194
Sun Nov 27 13:40:47 2016 SENT CONTROL [fr1.vyprvpn.com]: 'PUSH_REQUEST'
(status=
1)
Sun Nov 27 13:40:47 2016 AUTH: Received control message: AUTH_FAILED
Sun Nov 27 13:40:47 2016 SIGTERM[soft,auth-failure] received, process
exiting


2016-12-26 17:11 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by haugene** [comment]
Ok. First of all I see that vyprvpn ended up with the wrong name, should be VYPRVPN, but is VYPERVPN.
Second, your LOCAL_NETWORK variable is not valid. It says 192.168.0.1/253, but I guess you mean to put 192.168.0.1/24 which would allow all IPs in the range 192.168.0.0 to 192.168.0.255.

Then finally it seems the real problem is your username/password. The last error before exit is AUTH_FAILED.

**Comment by starsys** [comment]
Hello Kristian.
Thanks again for your help.
I tried all again from the beginning and corrected last mistakes I made.
My last log is :

Using OpenVPN provider: VYPERVPN
Starting OpenVPN using config France-160.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Fri Dec 30 19:34:13 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)]
[LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Fri Dec 30 19:34:13 2016 NOTE: the current --script-security setting may
allow this configuration to call user-defined scripts
Fri Dec 30 19:34:13 2016 Socket Buffers: R=[212992->131072]
S=[212992->131072]
Fri Dec 30 19:34:13 2016 UDPv4 link local: [undef]
Fri Dec 30 19:34:13 2016 UDPv4 link remote: [AF_INET]216.166.57.45:1194
Fri Dec 30 19:34:13 2016 TLS: Initial packet from [AF_INET]
216.166.57.45:1194, sid=33a4ac41 558faeef
Fri Dec 30 19:34:13 2016 WARNING: this configuration may cache passwords in
memory -- use the auth-nocache option to prevent this
Fri Dec 30 19:34:13 2016 VERIFY OK: depth=1, C=KY, ST=GrandCayman,
L=GeorgeTown, O=GoldenFrog-Inc, CN=GoldenFrog-Inc CA, emailAddress=
admin@goldenfrog.com
Fri Dec 30 19:34:13 2016 VERIFY X509NAME OK: C=KY, ST=GrandCayman,
L=GeorgeTown, O=GoldenFrog-Inc, CN=fr1.vyprvpn.com, emailAddress=
admin@goldenfrog.com
Fri Dec 30 19:34:13 2016 VERIFY OK: depth=0, C=KY, ST=GrandCayman,
L=GeorgeTown, O=GoldenFrog-Inc, CN=fr1.vyprvpn.com, emailAddress=
admin@goldenfrog.com
Fri Dec 30 19:34:16 2016 Data Channel Encrypt: Cipher 'BF-CBC' initialized
with 128 bit key
Fri Dec 30 19:34:16 2016 Data Channel Encrypt: Using 160 bit message hash
'SHA1' for HMAC authentication
Fri Dec 30 19:34:16 2016 Data Channel Decrypt: Cipher 'BF-CBC' initialized
with 128 bit key
Fri Dec 30 19:34:16 2016 Data Channel Decrypt: Using 160 bit message hash
'SHA1' for HMAC authentication
Fri Dec 30 19:34:16 2016 Control Channel: TLSv1, cipher TLSv1/SSLv3
DHE-RSA-AES256-SHA, 2048 bit RSA
Fri Dec 30 19:34:16 2016 [fr1.vyprvpn.com] Peer Connection Initiated with
[AF_INET]216.166.57.45:1194
Fri Dec 30 19:34:18 2016 SENT CONTROL [fr1.vyprvpn.com]: 'PUSH_REQUEST'
(status=1)
Fri Dec 30 19:34:18 2016 AUTH: Received control message: AUTH_FAILED
Fri Dec 30 19:34:18 2016 SIGTERM[soft,auth-failure] received, process
exiting

I've double checked my credentials : they are OK (login and password works
fine on other client)
Do you know why AUTH_FAILED ?


2016-12-29 18:42 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by haugene** [comment]
The username and password variables are put into a file in the container that openvpn reads from. You could check the contents of that file to ensure it looks correct. Running this command should output two lines, username first and then password.
`docker exec -it <container id/name> bash -c "cat /config/openvpn-credentials.txt"`

Does it look OK?

**Comment by starsys** [comment]
Hello Kristian.
Happy new year 2017 :-)

Can you please correct my command ? I get following result :
root@DS411:~# docker exec -it <TransmissionVPN> bash -c "cat
/config/openvpn-credentials.txt"
-ash: TransmissionVPN: No such file or directory


2017-01-01 22:02 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by haugene** [comment]
Happy new year! :)

Remove the <> part, that was just meant to serve as a placeholder. So:
`docker exec -it TransmissionVPN bash -c "cat
/config/openvpn-credentials.txt"`

**Comment by starsys** [comment]
Hello Kristian.
I had first following response :
root@DS411:~# docker exec -it TransmissionVPN bash -c "cat
/config/openvpn-credentials.txt"
Error response from daemon: Container
6f632eefe8154525ab2b2a6b2beade37c29aba220fd93b7000b9647c76bcc001 is not
running
Then I ran the container (runs just few seconds before crashing) ang got
following response :
root@DS411:~# docker exec -it TransmissionVPN bash -c "cat
/config/openvpn-credentials.txt"
"My user name"
"my password"

Everything seems to be ok.
I don't understand why I get an authentification failure...


2017-01-02 18:34 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by starsys** [comment]
Shouldn't I download a certificate ?
http://fr.giganews.com/support/vyprvpn/vpn-setup/linux/openvpn.html


2017-01-02 18:34 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by haugene** [comment]
Certificates should be included. 

But I'm not sure your parameters are good. 
If you get:
"username"
"password"

It's not correct as the " will be part of the strings. Should be just:
username
password

**Comment by starsys** [comment]
Yes it's only
username
password

Sorry


Le lun. 2 janv. 2017 à 20:01, Kristian Haugene <notifications@github.com> a
écrit :

**Comment by haugene** [comment]
Bah. Then I'm really not sure what to do, except checking that it's really the password you're supposed to use. With pia I have a separate username/password to log in to apps and using openvpn in the container. 

That part of the code is the same for all providers so the openvpn part should be ok. And it connects to the server, starts negotiating a connection but gets authentication failure. Have you checked with your provider?

**Comment by starsys** [comment]
Ok. I will contact them.
Thanks.

Le lun. 2 janv. 2017 à 20:15, Kristian Haugene <notifications@github.com> a
écrit :

**Comment by starsys** [comment]
Kristian : server adress should be : fr1.vpn.giganews.com
Can you please tell me how to update ?


2017-01-02 20:15 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by starsys** [comment]
Hello Kristian.
I've contacted Vyprvpn yesterday evening.
They helped me to find the failure (I assume) : the server adress for
france is not correct (see my previous mail).
Is it possible to update it ? How should I modify my configuration ?

Thanks again for your help


2017-01-02 20:15 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by starsys** [comment]
I try to find where is the France-160.ovpn
<https://github.com/haugene/docker-transmission-openvpn/blob/dev/openvpn/vypervpn/France-160.ovpn>
file
on my NAS to update it by I cannot find it.
Should I try to "pull" the updated file with a Docker command ?
Thanks in advance.

2017-01-02 20:15 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by cassegrain2** [comment]
Hello,

I have exatly the same problem as Starsys. Here is a log from docker:
[log.txt](https://github.com/haugene/docker-transmission-openvpn/files/692133/log.txt)

Any idea?

**Comment by dunestorm333** [comment]
Hi,
I'm also having the same issue when setting up my VyperVPN connection:

> Thu Jan 12 19:20:30 2017 [eu1.vyprvpn.com] Peer Connection Initiated with [AF_INET]216.166.57.35:443
stdout
Thu Jan 12 19:20:32 2017 SENT CONTROL [eu1.vyprvpn.com]: 'PUSH_REQUEST' (status=1)
stdout
Thu Jan 12 19:20:32 2017 AUTH: Received control message: AUTH_FAILED

**Comment by cassegrain2** [comment]
Hello guys,

I have found the issue in my case. They are two ways to connect to vyprvpn:
-Golden frog account, this is what has been set up as VYPRVPN at the moment.
-Giganews account. The address here is slightly different and that's why it did not work for me. You need to change the address to ***.giganews.com and it works like a charm.

Regards

**Comment by haugene** [comment]
I've now merged PR #190 from @cassegrain2, thanks again for helping out.
Could you verify that stuff is working as intended, and we can close this issue.
@dunestorm333 , @starsys

**Comment by starsys** [comment]
Hello Kristian. Can you please tell me which Dockers command I should use
to pull only the updated file ? (Or should I do it all again from the
beginning ?)
Thanks.

**Comment by haugene** [comment]
From the beginning :) The easiest solution is to pull the image again and create a new container. Remember to pull with the dev tag, and that should be it.

**Comment by starsys** [comment]
Ok, I'll try that asap. Thanks.

**Comment by starsys** [comment]
Hello Kristian.
I tried all again from the beginning : same issue.
I've checked the *France-256.ovpn* file on github : it's still the old "
fr1.vyprvpn.com" server adress.
In order to work properly, we have to use following one's : fr1.vpn
.giganews.com
Can you please update the *France-256.ovpn* file this way ?
Thanks in advance.

2017-01-02 21:21 GMT+01:00 Théophile Guettier <theophile.guettier@gmail.com>
:

**Comment by haugene** [comment]
Use provider GIGANEWS

**Comment by starsys** [comment]
Ah ok ! Sorry


Le lun. 6 févr. 2017 à 18:07, Kristian Haugene <notifications@github.com> a
écrit :

**Comment by starsys** [comment]
So I use GIGANEWS configuration.
I haven't the authentication problem anymore : good news.
Now I've a TUN/TAP error....
I've already created the TUN.sh file. I've to check what is going on...

Using OpenVPN provider: GIGANEWS

No VPN configuration provided. Using default.

Setting OPENVPN credentials...

adding route to local network 192.168.0.1/24 via 172.17.0.1 dev eth0

RTNETLINK answers: Operation not permitted

Mon Feb  6 17:08:44 2017 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL
(OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec
1 2014

Mon Feb  6 17:08:44 2017 NOTE: the current --script-security setting
may allow this configuration to call user-defined scripts

Mon Feb  6 17:08:44 2017 Socket Buffers: R=[212992-&gt;131072]
S=[212992-&gt;131072]

Mon Feb  6 17:08:44 2017 UDPv4 link local: [undef]

Mon Feb  6 17:08:44 2017 UDPv4 link remote: [AF_INET]216.166.57.139:443

Mon Feb  6 17:08:44 2017 TLS: Initial packet from
[AF_INET]216.166.57.139:443, sid=b3003219 057d1977

Mon Feb  6 17:08:44 2017 WARNING: this configuration may cache
passwords in memory -- use the auth-nocache option to prevent this

Mon Feb  6 17:08:44 2017 VERIFY OK: depth=1, C=KY, ST=GrandCayman,
L=GeorgeTown, O=GoldenFrog-Inc, CN=GoldenFrog-Inc CA,
emailAddress=admin@goldenfrog.com

Mon Feb  6 17:08:44 2017 VERIFY X509NAME OK: C=KY, ST=GrandCayman,
L=GeorgeTown, O=GoldenFrog-Inc, CN=eu1.vpn.giganews.com,
emailAddress=admin@goldenfrog.com

Mon Feb  6 17:08:44 2017 VERIFY OK: depth=0, C=KY, ST=GrandCayman,
L=GeorgeTown, O=GoldenFrog-Inc, CN=eu1.vpn.giganews.com,
emailAddress=admin@goldenfrog.com

Mon Feb  6 17:08:44 2017 Data Channel Encrypt: Cipher 'AES-256-CBC'
initialized with 256 bit key

Mon Feb  6 17:08:44 2017 Data Channel Encrypt: Using 256 bit message
hash 'SHA256' for HMAC authentication

Mon Feb  6 17:08:44 2017 Data Channel Decrypt: Cipher 'AES-256-CBC'
initialized with 256 bit key

Mon Feb  6 17:08:44 2017 Data Channel Decrypt: Using 256 bit message
hash 'SHA256' for HMAC authentication

Mon Feb  6 17:08:44 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3
DHE-RSA-AES256-SHA, 2048 bit RSA

Mon Feb  6 17:08:44 2017 [eu1.vpn.giganews.com] Peer Connection
Initiated with [AF_INET]216.166.57.139:443

Mon Feb  6 17:08:47 2017 SENT CONTROL [eu1.vpn.giganews.com]:
'PUSH_REQUEST' (status=1)

Mon Feb  6 17:08:47 2017 PUSH: Received control message:
'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS
10.11.139.1,explicit-exit-notify 5,rcvbuf 524288,route-gateway
10.11.139.1,topology subnet,ping 10,ping-restart 60,ifconfig
10.11.139.83 255.255.255.0'

Mon Feb  6 17:08:47 2017 OPTIONS IMPORT: timers and/or timeouts modified

Mon Feb  6 17:08:47 2017 OPTIONS IMPORT: explicit notify parm(s) modified

Mon Feb  6 17:08:47 2017 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified

Mon Feb  6 17:08:47 2017 Socket Buffers: R=[131072-&gt;425984]
S=[131072-&gt;131072]

Mon Feb  6 17:08:47 2017 OPTIONS IMPORT: --ifconfig/up options modified

Mon Feb  6 17:08:47 2017 OPTIONS IMPORT: route options modified

Mon Feb  6 17:08:47 2017 OPTIONS IMPORT: route-related options modified

Mon Feb  6 17:08:47 2017 OPTIONS IMPORT: --ip-win32 and/or
--dhcp-option options modified

Mon Feb  6 17:08:47 2017 ROUTE_GATEWAY 172.17.0.1/255.255.0.0
IFACE=eth0 HWADDR=02:42:ac:11:00:02

Mon Feb  6 17:08:47 2017 ERROR: Cannot open TUN/TAP dev /dev/net/tun:
No such file or directory (errno=2)

Mon Feb  6 17:08:47 2017 Exiting due to fatal error


2017-02-06 18:07 GMT+01:00 Kristian Haugene <notifications@github.com>:

**Comment by starsys** [comment]
Does anyone know where I should move my TUN.sh file ?
Error says :  "Cannot open TUN/TAP dev /dev/net/tun"

**Comment by haugene** [comment]
Shouldn't matter where it's moved, have you run it successfully? If you can't make it work I would go for just installing the openvpn package for the nas (without activating it) which should install the tun device. This is also mentioned in the readme.
