### ISSUE TITLE
[PIA] PIA custom script failed to download

### ISSUE THREAD

**Issue by gchapeyrout** [haugene/docker-transmission-openvpn#1579]
At first start, /openvpn/pia/configure-openvpn.sh try to download
 - https://www.privateinternetaccess.com/openvpn/openvpn-nextgen.zip
as explained in the documentation provided by PIA here:
 - https://www.privateinternetaccess.com/helpdesk/guides/linux/linux-uninstalling-the-pia-app-through-the-terminal

But right now, the file https://www.privateinternetaccess.com/openvpn/openvpn-nextgen.zip is not available anymore.

This produce the following error:

Starting container with revision: 3d97cd5302985c1a710f46ab0c311f721f224fc6
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.PiMlJO
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
unzip: short read

Regards

**Comment by gchapeyrout** [comment]
I've asked to PIA: They said that the URL is not valid anymore and that week-end should use URLs from this page:
https://www.privateinternetaccess.com/helpdesk/kb/articles/where-can-i-find-your-ovpn-files

So I guess that:
https://www.privateinternetaccess.com/openvpn/openvpn-nextgen.zip
Should be replaced by 
https://www.privateinternetaccess.com/openvpn/openvpn.zip

**Comment by gchapeyrout** [comment]
I've managed to start the container by this workaround:

I've added PIA_OPENVPN_CONFIG_BUNDLE=openvpn to the env.properties .

It works for me now.

**Comment by steve-spiteri** [comment]
If I am not mistaken, this is an issue in dev but it currently resolved in latest.

**Comment by tylerchambers** [comment]
@steve-spiteri it appears to be the other way around.

I was able to reproduce with latest, but not with dev. 

it looks like they changed the name of the open vpn config files, so I had to modify that (underscore instead of space) but everything appears to be working properly on dev now. 

for other PIA users having this problem, run the following: 

```bash
docker run --cap-add=NET_ADMIN -d \
              -v /your/data/dir/:/data \
              -e OPENVPN_PROVIDER=PIA \
              -e OPENVPN_CONFIG=us_east \
              -e OPENVPN_USERNAME=[your_username] \
              -e OPENVPN_PASSWORD=[your_password] \
              -e LOCAL_NETWORK=192.168.0.0/16 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn:dev
```
full list of configs [here](https://gist.github.com/tylerchambers/acdf6da7afb1e7906a0fb4f5a33f3dc4#file-gistfile1-txt)

**Comment by tylerdola** [comment]
> I've managed to start the container by this workaround:
> 
> I've added PIA_OPENVPN_CONFIG_BUNDLE=openvpn to the env.properties .
> 
> It works for me now.

Thank you very much, this worked for me too to get around this!

**Comment by redlukas** [comment]
> I've managed to start the container by this workaround:
> 
> I've added PIA_OPENVPN_CONFIG_BUNDLE=openvpn to the env.properties .
> 
> It works for me now.

This works for me too, but only if I write the OPENVPN_CONFIG env variables in all lower case, while the case did not matter with the PIA_OPENVPN_CONFIG_BUNDLE variavle unset.

**Comment by gchapeyrout** [comment]
Hello,

Yes, I forgot that I also had to modify the OPENVPN_CONFIG env variables to comply with new PIA syntax.

BTW, I also use latest image:
haugene/transmission-openvpn:latest
Id: sha256:654d394669603fd301ce2760f6e3cdde72dce95713e7a1028d52fa2e11a873be

I've connected to the running container and edited file /etc/openvpn/pia/configure-openvpn.sh
And it appears that line 12 is:
PIA_OPENVPN_CONFIG_BUNDLE=${PIA_OPENVPN_CONFIG_BUNDLE:-"openvpn-nextgen"}
Where it should be:
PIA_OPENVPN_CONFIG_BUNDLE=${PIA_OPENVPN_CONFIG_BUNDLE:-"openvpn"}
As it has been comited by jaller200 8 days ago:
https://github.com/haugene/docker-transmission-openvpn/commit/cc66a953493884b5ae02aa43ab6fa115b38234ad#diff-b232c678a4d721728f3b5c273846e2db11e654cc000b16c62ea2e397ad4ef705

**Comment by joe-eklund** [comment]
Just echoing that the fix for me was to change these lines in my docker-compose:

```
- PIA_OPENVPN_CONFIG_BUNDLE=openvpn-ip-nextgen
- OPENVPN_CONFIG=CA Toronto
```
to
```
- PIA_OPENVPN_CONFIG_BUNDLE=openvpn
- OPENVPN_CONFIG=ca_toronto
```

And it is working again on the latest docker image. Thanks friends.

**Comment by UniverseXXX** [comment]
yet again, after today's container update, I'm getting `curl: (6) Could not resolve host: www.privateinternetaccess.com`
I've tried to apply the above workaround, but it won't help.

**Comment by haugene** [comment]
This issue was fixed here https://github.com/haugene/docker-transmission-openvpn/pull/1552 (7 days before this issue was opened)
PIA also changed the config names as you've noticed, but that's their choice I guess. We just use their configs.

To those of you who have set `PIA_OPENVPN_CONFIG_BUNDLE=openvpn` it was a good workaround before the fix was committed to this repo, but now you will also have overridden it locally if the default changes again.

Anyways. I feel this issue can be closed.

@UniverseXXX You're experiencing something entirely different. That is a DNS issue. You should have a look [here](https://haugene.github.io/docker-transmission-openvpn/tips-tricks/#use_google_dns_servers). Or search for existing issues like #1564 or #1480. I'll make a note to add a separate section on this in the FAQ as well. Seems I need a better place to link to for these issues.

**Comment by UniverseXXX** [comment]
@haugene thanks for the prompt reply. I've got all those DNS parameters in my setup for quite a long time, nothing has been changed recently. Her is the particular part:
```
...
    dns:
      - 209.222.18.222
      - 84.200.69.80
      - 37.235.1.174
      - 1.1.1.1
      - 209.222.18.218
      - 37.235.1.177
      - 84.200.70.40
      - 1.0.0.1
      - 192.168.1.1
      - 10.0.0.242
...
      - OVERRIDE_DNS_1=10.0.0.242
      - OVERRIDE_DNS_2=209.222.18.222
      - OVERRIDE_DNS_3=84.200.69.80
      - OVERRIDE_DNS_4=37.235.1.174
      - OVERRIDE_DNS_5=209.222.18.218
      - OVERRIDE_DNS_6=37.235.1.177
      - OVERRIDE_DNS_7=84.200.70.40
      - OVERRIDE_DNS_8=1.1.1.1
      - OVERRIDE_DNS_9=192.168.1.1
...
```

All these been working fine for the last several weeks, the container has been updating regularly without any issues until today's update. I believe there was another update yesterday which was fine for me.

**Comment by haugene** [comment]
What if you remove all of that and only leave `OVERRIDE_DNS_1=8.8.8.8`?

**Comment by UniverseXXX** [comment]
> What if you remove all of that and only leave `OVERRIDE_DNS_1=8.8.8.8`?

just tried it - no luck.
I've also tried custom VPN configuration - used PIA default VPN configuration. Still getting can not resolve..
And finally tried PIA **IP** configuration which worked fine.

**Comment by haugene** [comment]
That would probably help you connect, yes. But it might still fail if some of the torrents refer to trackers by DNS name, which they normally do. If DNS works after you've connected then that points to your local network blocking something. But you need to create a separate issue for this. This issue is fixed and will be closed.
