### ISSUE TITLE
Latest Container Tag Fails on Start: ModuleNotFoundError: No module named 'ufw'

### ISSUE THREAD

**Issue by xcjs** [haugene/docker-transmission-openvpn#1816]
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** 
```latest```

*If possible, last working version:* 
 
```3.6```

### Describe the problem

**REQUIRED**
```txt
I currently use the Ouroboros container to automatically update containers. 
In this case, Ouroboros updated 3.6 to the current latest tag as of this time.

I've also paused Ouroboros and tried creating a container with the latest tag 
manually. The same issue results.

The final error message from the container log is: 

ModuleNotFoundError: No module named 'ufw'

This issue prevents the container from starting successfully.

A full log will follow below.
```

### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
1. I removed my container with docker rm -f transmission-openvpn
2. I started my container with the command specified below (docker run ...)
3. When the container tag is 3.6, the container works as expected.
4. When the container tag is latest, the container fails with the previously mentioned error message. 

I have also tried pruning any dangling images between container creations without much luck.
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
docker run -d \
        --name transmission-openvpn \
        --restart unless-stopped \
        --cap-add=NET_ADMIN \
        --device=/dev/net/tun \
        -v /mnt/varext/docker/transmission-openvpn:/data \
        -v /etc/localtime:/etc/localtime:ro \
        -e OPENVPN_PROVIDER=PIA \
        -e OPENVPN_USERNAME="${PIA_USERNAME}" \
        -e OPENVPN_PASSWORD="${PIA_PASSWORD}" \
        -e OPENVPN_CONFIG="belgium" \
        -e ENABLE_UFW=true \
        -e TRANSMISSION_WEB_UI=combustion \
        -e OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60" \
        -e LOCAL_NETWORK=192.168.0.0/16 \
        -p 9091:9091 \
        --dns 8.8.8.8 \
        --dns 8.8.4.4 \
        haugene/transmission-openvpn:latest
```

### Logs

 

**REQUIRED**
```txt
Starting container with revision: 416541016b9b30149d8fcb56abe2bc325db4904b
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.odOoFe
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Starting OpenVPN using config belgium.ovpn
Modifying /etc/openvpn/pia/belgium.ovpn for best behaviour in this container
Setting OpenVPN credentials...
enabling firewall
Traceback (most recent call last):
  File "/usr/sbin/ufw", line 25, in <module>
    import ufw.frontend
ModuleNotFoundError: No module named 'ufw'
```

### Host system

**REQUIRED**
```txt
Operating System:

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

Kernel Information: Linux USERV 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Docker Version: Docker version 20.10.6, build 370c289
```

**Comment by pkishino** [comment]
Hmm, there has been no change to build since 3.6 so this does not make any sense..
I did take a look at the circleci build logs..
the only diff regarding ufw is that tag 3.6 uses ufw@community 0.36-rc3 and latest rc4 ..but couldn't find any bug or so on ufw bug tracker..strange

**Comment by xcjs** [comment]
Something else I wanted to add - I did see this behavior on two servers I run.

Both run the same versions of Docker and operating system. Updates are controlled via Ansible.

**Comment by pkishino** [comment]
think I found the issue..
python3 (3.8.8-r0)
#8 17.72 (58/60) Installing ufw@community (0.36-r4)
0.36-r4 wants python 3.9>

**Comment by pkishino** [comment]
yeah, issue found..we are using community on edge which is wrong..
will push a fix in a sec

**Comment by pkishino** [comment]
should be fixed in  commit e775d4c now

**Comment by pkishino** [comment]
will take a bit until circleci builds etc

**Comment by pkishino** [comment]
please test and close when you can confirm

**Comment by xcjs** [comment]
Awesome! I'll take a look at it tomorrow evening.

**Comment by UniverseXXX** [comment]
@pkishino Thanks for quick fixing. I can confirm that it's working now. I'm still seeing the following error, though not sure if it's related to the above:

`2021-04-22 12:58:37 ERROR: Linux route -6 add command failed: external program exited with error status: 2`

**Comment by pkishino** [comment]
Hmm, I’ll see if I can track it down tomorrow

**Comment by joe-eklund** [comment]
Since I cannot respond to the other comment you made in the other thread, I will respond here.

> Recommending people to switch to dev tag isn't really a good idea as
> a) dev is just that, in development state and possibly unstable, causing potential unnecessary issues for users etc

Sure, I agree in theory. But in practice, when someone just wants something to work, and no one but me had offered a **temporary** workaround, I don't think people actually care. Yes, the underlying issue should probably be resolved, but if I didn't want to wait around for days without a working application I think my suggestion was completely reasonable given the context that no one else gave any useful advice at the time. I just tried a different image, it worked, posted the OP try that, and moved on with my life.

> b) is bad practice as a better first step would be a rollback to previous working version

Definitely a fair argument. I believe the tag `3.6` is the last working tag I could find. That is what I think people should be using in the meantime.

> c) makes it harder for us to fix as then, instead of helping out to find the issue, users will just ignore and move on..

Well if it was fixed in `dev`, I was under the impression the bug had been fixed. Though I understand where you are coming from.

**Comment by pkishino** [comment]
I take it this can be closed due to confirmation of at least one other person

**Comment by xcjs** [comment]
It's the issue that @UniverseXXX discovered resolved? That makes me concerned that a firewall rule isn't getting defined correctly.

**Comment by pkishino** [comment]
Well, I can’t do much based on the little snippet of log..I haven’t seen this in my logs so best would be to create a new issue and try to address it there
