### ISSUE TITLE
No download. Cannot connect to any tracker

### ISSUE THREAD

**Issue by rwaesely** [haugene/docker-transmission-openvpn#260]
Hello haugene, 
I have your awesome docker running on my synology with DSM 6.1, along with HMA subscription.
Everything was working fine since a few weeks (remember me ? had an issue solved by running with root user instead of my own).
Unfortunately, the container runs since a few days without any download. It cannot connect to any tracker. I tried changing the settings with the -e parameter :
`-e "OPENVPN_CONFIG=Switzerland.Zurich_LOC1S1.TCP" \` with no luck. Don't know if it is the right way to do it... but I have no other idea.
If it can help, I keep having this issue on my logs 

`2017-06-21 17:40:36,stdout,Wed Jun 21 17:40:36 2017 write to TUN/TAP : Invalid argument (code=22)`
I noticed when I run a bash on my container that it cannot ping Google for instance ! which is quite weird, isn't it ?
Hope you'll make me find the holy truth :)

**Comment by rwaesely** [comment]
Maybe it can help to find a solution : I opened a bash on the container, and it is not possible to ping any server with its DNS, just like if the resolution by name was not working anymore. However, I never did the test before this issue, so I lack some elements of comparison...

**Comment by rwaesely** [comment]
Hi. Apparently the container does not work anymore with HMA on synology platform. Anybody experiencing similar issue ?

**Comment by rwaesely** [comment]
I tried updating the base image of the dockerfile, updating each piece of library used in the docker file, with no success ;-(
Result is still the same : the container run, with no possibility to connect to any tracker 'cause it does not find them. Maybe it does not find the gateway. Somebody, help, please...

**Comment by rwaesely** [comment]
Still the same with updated version of the container. No connection when using default config with HMA, but the container event does not start when specifying a config file. @haugene are you sure these config files are up-to-date with HMA? when I download them directly from HMA, There is no UDP or TCP file for instance.

**Comment by haugene** [comment]
Should at least be updated using the dev tag since I merged #263? If you pass me a link to the openvpn config files download I can have another look. But try the dev tag first if you haven't already.

**Comment by rwaesely** [comment]
how am I supposed to accomplish that ? Just a git clone ? because when I tried a git clone, it was not working unless I add some commands in the dockerfile to add execution rights to binaries and shell scripts :-/
Thanks for your patience...

**Comment by rwaesely** [comment]
As expected, I got the same error : [dumb-init] /etc/openvpn/start.sh: Permission denied

**Comment by rwaesely** [comment]
added chmod +x on scripts, container is running... still the same, cannot find any tracker. Thanks again for your time haugene.

**Comment by Guimove** [comment]
Hello, just to inform that I have the same issue.

**Comment by Guimove** [comment]
It's ok now for me.

2 Steps : 

1. use DEV branch so I used "docker run ..... haugene/transmission-openvpn:dev" ==> I now have internet but no torrent
2. by default US is used by HMA and they are blocking torrent... just changed to netherland ==> Torrent OK now

**Comment by rwaesely** [comment]
Thanks Guimove, I give a try this evening, keep you informed :)

**Comment by haugene** [comment]
If the US gateways are blocking torrents that makes a lot of sense. Changed the default to Netherlands now. You should now be able to use the dev tag without further modifications @rwaesely, can you confirm it's working?

And thanks for pointing it out @Guimove :)

**Comment by Guimove** [comment]
You're welcome ;)

Your commit is exactly the change  I've made

**Comment by rwaesely** [comment]
It's working, alleluia bros ! \o/

**Comment by andrijaperovic** [comment]
Ran into same issue on windscribe, couldn't connect to udp trackers, netherlands-udp worked like a charm 👍 thanks @Guimove @haugene
